[options]
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
Color
ParallelDownloads = 5
CheckSpace

#
# CachyOS repositories (RESMI)
#
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[cachyos-v3]
Include = /etc/pacman.d/cachyos-mirrorlist

#
# Arch Linux repositories
#
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
