#
# /etc/pacman.conf — CLEAN CACHYOS
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ParallelDownloads = 5
CheckSpace
VerbosePkgLists
ILoveCandy

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

#
# CACHYOS REPOSITORIES
#
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[cachyos-v3]
Include = /etc/pacman.d/cachyos-mirrorlist

#
# ARCH LINUX REPOSITORIES
#
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
